name: Pull Request CI

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            LANGUAGE_MODEL: ${{ secrets.LANGUAGE_MODEL }}
            VISION_MODEL: ${{ secrets.VISION_MODEL }}
            TEXT_MODEL: ${{ secrets.TEXT_MODEL }}

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  echo ${{ secrets.VISION_MODEL }}
                  EEE=${{ secrets.VISION_MODEL }} echo "$EEE"
